### ISSUE TITLE
FancyMumble support for Chinese

### ISSUE THREAD

**Issue by FutabaWasuke** [Fancy-Mumble/FancyMumbleV2#83]
Hi, I am a user from China. Our community often uses Mumble for discussions, so I hope FancyMumble can provide Chinese support.

If there is Weblate, maybe we can help you complete Chinese localization.

**Comment by SetZero** [comment]
Hello @FutabaWasuke , 
thank you for creating this ticket. Currently Fancy Mumble doesn't have any support for i18n, so I've created the ticket #84 add this support. I'll have a look into this and update the ticket when it's ready

**Comment by FutabaWasuke** [comment]
@SetZero 
Thank you for your reply, I will be happy to help you with Chinese localization once you have multi-language support ready.
Looking forward to any updates from FancyMumble, thanks for the development

**Comment by FutabaWasuke** [comment]
> Hello @FutabaWasuke , thank you for creating this ticket. Currently Fancy Mumble doesn't have any support for i18n, so I've created the ticket #84 add this support. I'll have a look into this and update the ticket when it's ready

Hi, I noticed that Fancy Mumble already supports multiple languages. Then I translated and replaced the English of the json file in the source code. If I was not negligent, it should be usable. 

How should I submit these translations to you? 

I don't know if I should pull request because I don't have the conditions to do any testing.😭

**Comment by SetZero** [comment]
Hi,
I started adding multi language support with the last release. Most directly visible things should be translatable. There are still some error messages and chat log content which has not yet been added.

I just haven't answered to this ticket, because I didn't have time yet to set something up to make translating easier (like Weblate). 

But if you already have something using the json files you can create a PR and I'll have a look at it.

**Comment by SetZero** [comment]
With #88 merged I'll try to get a release with the changes and some other improvements I did ready at the end of the week. Thanks again for your help!

**Comment by SetZero** [comment]
I'm closing this ticket, because it is now part of release 0.2.2
